name: Rust CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build step"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Compile
      run: cargo build --verbose

  test:
    name: "Test & Coverage"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: "Setup toolchain: nightly"
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --no-fail-fast   
      env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads'
    - id: coverage
      name: Build coverage data
      uses: actions-rs/grcov@v0.1.5
    - name: Debug steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file:  ${{ steps.coverage.outputs.report }}
        fail_ci_if_error: false
        flags: unittests
